# Generated by Django 5.2.5 on 2025-08-25 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Honor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='None', max_length=100)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, default='avatars/default.png', upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255)),
                ('is_done', models.BooleanField(default=False)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileHonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validity_period', models.PositiveIntegerField(blank=True, null=True)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('bought', models.BooleanField(default=False)),
                ('honor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_honors', to='profiles.honor')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_honors', to='profiles.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='honors',
            field=models.ManyToManyField(through='profiles.ProfileHonor', to='profiles.honor'),
        ),
        migrations.AddConstraint(
            model_name='profilehonor',
            constraint=models.UniqueConstraint(fields=('profile', 'honor'), name='uniq_profile_honor'),
        ),
    ]
